################################################################################################
#
# 本地测试环境
#
################################################################################################

# 端口配置
server:
  port: 8080
  servlet:
    context-path: /

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapping/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.entity  # 注意：对应实体类的路径
  configuration:
    call-setters-on-nulls: true

# spring 基础配置
spring:
  # mysql 配置
  datasource:
    url: jdbc:mysql://192.168.1.153:3306/business_registration?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&allowMultiQueries=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: PXXyqx@2017




