package com.example.demo.entity;


import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.io.Serializable;
import java.util.Date;
@Data
@TableName(value = "teacher")//指定表名
public class Teacher implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated
     */
    @TableId(value = "id")
    private Integer id;

    @TableField(value = "name",exist = true)
    private String name;
    private String subject;

    @TableField(value = "create_date",exist = true)
    private Date  createDate;

    private static final long serialVersionUID = 1L;

    public void setName(String name) {
        this.name = name +"123123123";
    }
}